import Head from "next/head";
import React from "react";

const PageMeta = ({ title = "LinkedIn 2.0" }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageMeta;
