import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import HeaderLink from "../components/HeaderLink";

export default function Home() {
  return (
    <div>
      <Head>
        <title>LinkedIn 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-around items-center py-4">
        <div className="relative w-36 h-10">
          <Image
            src="https://content.linkedin.com/content/dam/me/business/en-us/amp/brand-site/v2/bg/LI-Logo.svg.original.svg"
            alt="brand-logo"
            layout="fill"
            objectFit="contain"
          />
        </div>
        <div className="flex items-center sm:divide-x divide-gray-300">
          <div className="hidden sm:flex space-x-8 pr-4">
            <HeaderLink />
          </div>
        </div>
      </header>
    </div>
  );
}
